# Generated by Django 4.2.25 on 2025-11-01 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('sale', 'Sale'), ('purchase', 'Purchase'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('checkup', 'Health Checkup'), ('breeding', 'Breeding'), ('weaning', 'Weaning'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('veterinarian', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='animals.animal')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'), models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'), models.Index(fields=['animal'], name='events_even_animal__2bae93_idx')],
            },
        ),
    ]
