# Generated by Django 4.2.25 on 2025-11-01 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('acquisition_date', models.DateField()),
                ('acquisition_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('pregnant', 'Pregnant'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('last_checkup', models.DateField(blank=True, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('mother_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('father_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='owners.owner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tag_id'], name='animals_ani_tag_id_5fbaf6_idx'), models.Index(fields=['species'], name='animals_ani_species_9bedc5_idx'), models.Index(fields=['status'], name='animals_ani_status_e5c501_idx')],
            },
        ),
    ]
