# Generated by Django 4.2.25 on 2025-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('inventory', 'Inventory Report'), ('health', 'Health Report'), ('financial', 'Financial Report'), ('breeding', 'Breeding Report'), ('custom', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'), models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx')],
            },
        ),
    ]
